import asyncio
import uuid
from sqlalchemy import select
from app.core.database import async_session_factory
from app.core.logging import logger
from app.models import (
    InventoryItem,
    LedgerReason,
    Location,
    Product,
    ProductVariant,
    StockLedgerEntry,
    User,
    UserRole,
)

IDOL_PRODUCTS_DATA = [
    {
        "name": "Handcrafted Cow Krishna Bansuri Idol",
        "slug": "handcrafted-cow-krishna-bansuri-idol",
        "deity": "Shri Krishna",
        "deity_form": "Kamadhenu Krishna playing Bansuri on Lotus",
        "material": "White Marble Resin",
        "material_purity": "High-Density Marble Resin with Hand-Painted Accents",
        "base_price": 38500,
        "original_price": 44000,
        "discount_badge": "Kamadhenu Blessings",
        "sku": "SRA-KR-01",
        "atelier": "Jaipur Atelier",
        "short_description": "Exquisite white marble resin Krishna standing on pink lotus with Kamadhenu cow playing golden bansuri.",
        "long_description": "Hand-sculpted by master artisans in Jaipur. Represents peace, abundance, and divine protection of all living beings.",
        "certificate_number": "SRA-CERT-2026-KR01",
        "is_featured_masterpiece": True,
        "featured_order": 1,
        "specifications": {"Weight": "11.2 kg", "Finish": "Saffron & Gold Hand-Painted", "Craftsmanship Time": "21 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with soft damp cloth; Ganga Jal spray compatible.", "Placement": "Northeast altar"},
        "images": [{"url": "/static/idols/cow-krishna-bansuri-idol.png", "alt": "Handcrafted Cow Krishna Bansuri Idol", "is_primary": True}],
        "tags": ["Krishna", "Kamadhenu", "Marble Resin", "Bansuri"],
        "variants": [{"size": "15-inch", "material": "White Marble Resin", "finish": "Saffron & Gold Hand-Painted", "base_price": 38500, "price_delta": 0, "sku": "SRA-KR-01-15", "stock": {"JPR": 4, "KSH": 2}}],
    },
    {
        "name": "White Marble Pure Shvetambara Krishna Murti",
        "slug": "white-marble-pure-shvetambara-krishna-murti",
        "deity": "Shri Krishna",
        "deity_form": "Tribhanga Muralidhar in Shvetambara Vastra",
        "material": "Pure Makrana White Marble",
        "material_purity": "Grade-A White Marble with 24K Gold Foil Lines",
        "base_price": 45000,
        "original_price": 50000,
        "discount_badge": "Shvetambara Pure",
        "sku": "SRA-KR-02",
        "atelier": "Jaipur Atelier",
        "short_description": "Pure white marble Krishna standing in Tribhanga pose with golden embroidered white vastra.",
        "long_description": "Sculpted in serene Makrana marble with delicate 24K gold lining along the draped garments.",
        "certificate_number": "SRA-CERT-2026-KR02",
        "is_featured_masterpiece": True,
        "featured_order": 2,
        "specifications": {"Weight": "13.5 kg", "Finish": "Polished Pure White & 24K Gold Foil", "Craftsmanship Time": "24 Days"},
        "seva_guidelines": {"Abhishekam": "Suitable for mild water and milk snana.", "Placement": "East facing home altar"},
        "images": [{"url": "/static/idols/white-marble-shvetambara-krishna.png", "alt": "White Marble Pure Shvetambara Krishna Murti", "is_primary": True}],
        "tags": ["Krishna", "White Marble", "Shvetambara", "Gold Foil"],
        "variants": [{"size": "18-inch", "material": "Pure Makrana White Marble", "finish": "Gold Foil Trimming", "base_price": 45000, "price_delta": 0, "sku": "SRA-KR-02-18", "stock": {"JPR": 3, "KSH": 3}}],
    },
    {
        "name": "Sanjeevani Parvat Dhari Hanuman Ji Idol",
        "slug": "sanjeevani-parvat-dhari-hanuman-ji-idol",
        "deity": "Shri Hanuman",
        "deity_form": "Dronagiri Sanjeevani Parvat Dhari Hanuman",
        "material": "High-Grade White Marble Composite",
        "material_purity": "Fine Marble Composite with 24K Gold Embellishments",
        "base_price": 32000,
        "original_price": 36000,
        "discount_badge": "Sankat Mochan Edition",
        "sku": "SRA-HN-03",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Viratan Hanuman Ji leaping over clouds carrying Sanjeevani Dronagiri mountain.",
        "long_description": "Symbolizing supreme devotion, strength, and victory over illness and obstacles.",
        "certificate_number": "SRA-CERT-2026-HN03",
        "is_featured_masterpiece": True,
        "featured_order": 3,
        "specifications": {"Weight": "10.8 kg", "Finish": "White Marble & Gold Ornaments", "Craftsmanship Time": "18 Days"},
        "seva_guidelines": {"Abhishekam": "Rinse with sacred water; offer Sindoor and Jasmine oil.", "Placement": "South or East wall"},
        "images": [{"url": "/static/idols/sanjeevani-parvat-dhari-hanuman.png", "alt": "Sanjeevani Parvat Dhari Hanuman Ji Idol", "is_primary": True}],
        "tags": ["Hanuman", "Sanjeevani", "Sankat Mochan", "Gold Gada"],
        "variants": [{"size": "14-inch", "material": "White Marble Composite", "finish": "Gold Ornaments", "base_price": 32000, "price_delta": 0, "sku": "SRA-HN-03-14", "stock": {"JPR": 5, "KSH": 3}}],
    },
    {
        "name": "Vasudeva Yamuna Par Krishna Leela Statue",
        "slug": "vasudeva-yamuna-par-krishna-leela-statue",
        "deity": "Vasudeva & Bal Krishna",
        "deity_form": "Vasudeva Crossing Yamuna River with Sheshnaag",
        "material": "Handcrafted Resin & Polymer Composite",
        "material_purity": "Weatherproof Resin Composite with Hand-Painted Details",
        "base_price": 28000,
        "original_price": 32000,
        "discount_badge": "Janmashtami Special",
        "sku": "SRA-KL-04",
        "atelier": "Jaipur Atelier",
        "short_description": "Vasudeva carrying newborn Bal Krishna in a basket across the Yamuna river under Sheshnaag.",
        "long_description": "Captures the iconic miraculous night of Krishna Janmashtami with vibrant river and serpent detailing.",
        "certificate_number": "SRA-CERT-2026-KL04",
        "is_featured_masterpiece": True,
        "featured_order": 4,
        "specifications": {"Weight": "8.5 kg", "Finish": "Multi-Color Hand-Painted", "Craftsmanship Time": "15 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe clean with microfiber cloth.", "Placement": "Home temple or showcase altar"},
        "images": [{"url": "/static/idols/vasudeva-yamuna-krishna-leela.png", "alt": "Vasudeva Yamuna Par Krishna Leela Statue", "is_primary": True}],
        "tags": ["Vasudeva", "Bal Krishna", "Janmashtami", "Yamuna Leela"],
        "variants": [{"size": "12-inch", "material": "Resin Composite", "finish": "Multi-Color", "base_price": 28000, "price_delta": 0, "sku": "SRA-KL-04-12", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Vaikuntha Shesh Shaiya Lakshmi Narayan Murti",
        "slug": "vaikuntha-shesh-shaiya-lakshmi-narayan-murti",
        "deity": "Lakshmi Narayan",
        "deity_form": "Lord Vishnu and Goddess Lakshmi on Sheshnaag Bed",
        "material": "Polished Resin & Marble Matrix",
        "material_purity": "Mineral-Filled Resin Matrix with 24K Gold Leaf Embellishment",
        "base_price": 58000,
        "original_price": 65000,
        "discount_badge": "Vaikuntha Masterpiece",
        "sku": "SRA-LN-05",
        "atelier": "Jaipur Atelier",
        "short_description": "Lord Vishnu and Goddess Lakshmi seated together on Sheshnaag in Kshira Sagara.",
        "long_description": "Ornate representation of cosmic harmony, prosperity, and eternal divine protection.",
        "certificate_number": "SRA-CERT-2026-LN05",
        "is_featured_masterpiece": True,
        "featured_order": 5,
        "specifications": {"Weight": "15.0 kg", "Finish": "Gold Leaf & Hand-Painted Details", "Craftsmanship Time": "28 Days"},
        "seva_guidelines": {"Abhishekam": "Gently wipe with damp cloth; keep away from harsh chemicals.", "Placement": "Main sanctum"},
        "images": [{"url": "/static/idols/vaikuntha-shesh-shaiya-lakshmi-narayan.png", "alt": "Vaikuntha Shesh Shaiya Lakshmi Narayan Murti", "is_primary": True}],
        "tags": ["Lakshmi Narayan", "Vishnu", "Lakshmi", "Sheshnaag", "Vaikuntha"],
        "variants": [{"size": "16-inch", "material": "Polished Resin & Marble Matrix", "finish": "Gold Leaf", "base_price": 58000, "price_delta": 0, "sku": "SRA-LN-05-16", "stock": {"JPR": 2, "KSH": 2}}],
    },
    {
        "name": "Makhan Chor Bal Gopal White Marble Statue",
        "slug": "makhan-chor-bal-gopal-white-marble-statue",
        "deity": "Bal Krishna",
        "deity_form": "Laddu Gopal Kneeling with Golden Butter Matki",
        "material": "Pure White Marble",
        "material_purity": "Hand-Carved White Marble with Gold Foil Accents",
        "base_price": 24000,
        "original_price": 28000,
        "discount_badge": "Best Seller",
        "sku": "SRA-BG-06",
        "atelier": "Jaipur Atelier",
        "short_description": "Adorable kneeling Bal Gopal eating butter from an ornate golden matki.",
        "long_description": "Handcrafted white marble sculpture bringing joy, innocence, and sweetness into your home altar.",
        "certificate_number": "SRA-CERT-2026-BG06",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "7.2 kg", "Finish": "Polished White Marble & Gold", "Craftsmanship Time": "14 Days"},
        "seva_guidelines": {"Abhishekam": "Suitable for regular water washing and vastra seva.", "Placement": "Home temple"},
        "images": [{"url": "/static/idols/makhan-chor-bal-gopal-white-marble.png", "alt": "Makhan Chor Bal Gopal White Marble Statue", "is_primary": True}],
        "tags": ["Bal Gopal", "Laddu Gopal", "Makhan Chor", "White Marble"],
        "variants": [{"size": "10-inch", "material": "Pure White Marble", "finish": "Gold Accents", "base_price": 24000, "price_delta": 0, "sku": "SRA-BG-06-10", "stock": {"JPR": 6, "KSH": 4}}],
    },
    {
        "name": "Yashoda Nandan Bal Krishna Marble Sculpture",
        "slug": "yashoda-nandan-bal-krishna-marble-sculpture",
        "deity": "Yashoda & Bal Krishna",
        "deity_form": "Mata Yashoda Embracing Little Krishna",
        "material": "White Marble Composite",
        "material_purity": "High-Grade White Marble Resin",
        "base_price": 36000,
        "original_price": 40000,
        "discount_badge": "Vatsalya Collection",
        "sku": "SRA-YK-07",
        "atelier": "Jaipur Atelier",
        "short_description": "Heartwarming white marble sculpture of Mata Yashoda embracing young Bal Krishna.",
        "long_description": "Encapsulates maternal affection (Vatsalya Bhava) with delicate pink lotus base and gold trimmings.",
        "certificate_number": "SRA-CERT-2026-YK07",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "9.8 kg", "Finish": "White Marble & Soft Pink Pedestal", "Craftsmanship Time": "18 Days"},
        "seva_guidelines": {"Abhishekam": "Clean softly with cotton cloth.", "Placement": "Family prayer area"},
        "images": [{"url": "/static/idols/yashoda-nandan-bal-krishna.png", "alt": "Yashoda Nandan Bal Krishna Marble Sculpture", "is_primary": True}],
        "tags": ["Yashoda", "Bal Krishna", "Vatsalya", "Marble Statue"],
        "variants": [{"size": "13-inch", "material": "White Marble Composite", "finish": "Soft Pink Base", "base_price": 36000, "price_delta": 0, "sku": "SRA-YK-07-13", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "White Marble Divine Radha Krishna with Sacred Cow",
        "slug": "white-marble-divine-radha-krishna-with-sacred-cow",
        "deity": "Radha Krishna",
        "deity_form": "Radha Krishna Yugal with Kamadhenu",
        "material": "Pure White Makrana Marble",
        "material_purity": "Grade-A Pure White Marble",
        "base_price": 52000,
        "original_price": 58000,
        "discount_badge": "Grace Edition",
        "sku": "SRA-RK-08",
        "atelier": "Jaipur Atelier",
        "short_description": "Serene pure white marble Radha Krishna pair with Kamadhenu cow and gold foil accents.",
        "long_description": "Crafted from single-block white marble in Jaipur. Features elegant golden trimmings and serene facial carving.",
        "certificate_number": "SRA-CERT-2026-RK08",
        "is_featured_masterpiece": True,
        "featured_order": 6,
        "specifications": {"Weight": "14.8 kg", "Finish": "Pure White & Gold Embossing", "Craftsmanship Time": "25 Days"},
        "seva_guidelines": {"Abhishekam": "Safe for regular sacred snana.", "Placement": "Main shrine altar"},
        "images": [{"url": "/static/idols/white-marble-radha-krishna-cow.png", "alt": "White Marble Divine Radha Krishna with Sacred Cow", "is_primary": True}],
        "tags": ["Radha Krishna", "White Marble", "Kamadhenu", "Yugal Sarkar"],
        "variants": [{"size": "16-inch", "material": "Pure White Makrana Marble", "finish": "Gold Embossing", "base_price": 52000, "price_delta": 0, "sku": "SRA-RK-08-16", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Hand-Painted Vrindavan Yugal Radha Krishna Idol",
        "slug": "hand-painted-vrindavan-yugal-radha-krishna-idol",
        "deity": "Radha Krishna",
        "deity_form": "Multi-Colored Radha Krishna Yugal on Pink Lotus",
        "material": "Hand-Painted Resin Composite",
        "material_purity": "High-Strength Resin with Micro-Pigment Coating",
        "base_price": 42000,
        "original_price": 48000,
        "discount_badge": "Vrindavan Colors",
        "sku": "SRA-RK-09",
        "atelier": "Jaipur Atelier",
        "short_description": "Vibrantly hand-painted Radha Krishna standing together on a blooming pink lotus blossom.",
        "long_description": "Adorned in classic Vrindavan ghagra-choli and saffron dhoti with rich golden ornamentation.",
        "certificate_number": "SRA-CERT-2026-RK09",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "11.0 kg", "Finish": "Vibrant Hand-Painted Resin", "Craftsmanship Time": "20 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with damp cloth.", "Placement": "Living temple"},
        "images": [{"url": "/static/idols/vrindavan-yugal-radha-krishna.png", "alt": "Hand-Painted Vrindavan Yugal Radha Krishna Idol", "is_primary": True}],
        "tags": ["Radha Krishna", "Vrindavan", "Lotus Base", "Hand-Painted"],
        "variants": [{"size": "15-inch", "material": "Hand-Painted Resin Composite", "finish": "Vibrant Colors", "base_price": 42000, "price_delta": 0, "sku": "SRA-RK-09-15", "stock": {"JPR": 4, "KSH": 3}}],
    },
    {
        "name": "Pastel Elegance Radha Krishna Dual Murti Pair",
        "slug": "pastel-elegance-radha-krishna-dual-murti-pair",
        "deity": "Radha Krishna",
        "deity_form": "Dual Standalone Sculptures in Pastel Lilac & Mint Green",
        "material": "Polished Marble Resin",
        "material_purity": "Premium Polymer Composite with Pastel Lacquer",
        "base_price": 64000,
        "original_price": 72000,
        "discount_badge": "Signature Pair",
        "sku": "SRA-RK-10",
        "atelier": "Jaipur Atelier",
        "short_description": "Exclusive twin statue pair of Radha and Krishna in subtle pastel lilac and mint green hues.",
        "long_description": "A sophisticated modern sanctuary centerpiece featuring two separate individual statues on carved lotus pedestals.",
        "certificate_number": "SRA-CERT-2026-RK10",
        "is_featured_masterpiece": True,
        "featured_order": 7,
        "specifications": {"Weight": "18.2 kg (Set of 2)", "Finish": "Pastel Matte Luster", "Craftsmanship Time": "30 Days"},
        "seva_guidelines": {"Abhishekam": "Gently spray sacred water; wipe dry.", "Placement": "Sanctum center pair"},
        "images": [{"url": "/static/idols/pastel-radha-krishna-pair.png", "alt": "Pastel Elegance Radha Krishna Dual Murti Pair", "is_primary": True}],
        "tags": ["Radha Krishna", "Pastel Edition", "Dual Murti", "Signature"],
        "variants": [{"size": "18-inch Pair", "material": "Polished Marble Resin", "finish": "Pastel Matte", "base_price": 64000, "price_delta": 0, "sku": "SRA-RK-10-18", "stock": {"JPR": 2, "KSH": 1}}],
    },
    {
        "name": "Meditative Shanti Buddha Marble Statue",
        "slug": "meditative-shanti-buddha-marble-statue",
        "deity": "Gautam Buddha",
        "deity_form": "Padmasana Buddha in Maroon Robe with Golden Lotus",
        "material": "White Marble Composite",
        "material_purity": "White Marble Resin with Deep Maroon Sanghati",
        "base_price": 29000,
        "original_price": 33000,
        "discount_badge": "Peace Edition",
        "sku": "SRA-BD-12",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Meditating Buddha in deep maroon robe with gold trim holding golden lotus in Abhaya Mudra.",
        "long_description": "Inspires calmness, mindfulness, and spiritual focus for meditation halls and serene home corners.",
        "certificate_number": "SRA-CERT-2026-BD12",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "8.9 kg", "Finish": "Maroon & Gold Lacquer", "Craftsmanship Time": "16 Days"},
        "seva_guidelines": {"Abhishekam": "Clean with dry microfiber duster.", "Placement": "Meditation room or entrance foyer"},
        "images": [{"url": "/static/idols/meditative-shanti-buddha-maroon.png", "alt": "Meditative Shanti Buddha Marble Statue", "is_primary": True}],
        "tags": ["Buddha", "Meditation", "Shanti", "Abhaya Mudra"],
        "variants": [{"size": "14-inch", "material": "White Marble Composite", "finish": "Maroon & Gold", "base_price": 29000, "price_delta": 0, "sku": "SRA-BD-12-14", "stock": {"JPR": 4, "KSH": 2}}],
    },
    {
        "name": "Black & White Dual Tone Bhumisparsha Buddha Idol",
        "slug": "black-and-white-dual-tone-bhumisparsha-buddha-idol",
        "deity": "Gautam Buddha",
        "deity_form": "Dual Tone Black & White Bhumisparsha Mudra",
        "material": "Polished Marble Composite",
        "material_purity": "High-Gloss Dual-Tone Polished Composite",
        "base_price": 34000,
        "original_price": 38000,
        "discount_badge": "Zen Collection",
        "sku": "SRA-BD-13",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Striking dual-tone Buddha featuring glossy black torso and pristine white sanghati robe.",
        "long_description": "Earth-touching Bhumisparsha posture representing enlightenment and witness to truth.",
        "certificate_number": "SRA-CERT-2026-BD13",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "10.4 kg", "Finish": "Glossy Dual Tone Black-White", "Craftsmanship Time": "18 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with soft lint-free cloth.", "Placement": "Zen corner or living space"},
        "images": [{"url": "/static/idols/dual-tone-bhumisparsha-buddha.png", "alt": "Black & White Dual Tone Bhumisparsha Buddha Idol", "is_primary": True}],
        "tags": ["Buddha", "Bhumisparsha", "Dual Tone", "Zen"],
        "variants": [{"size": "15-inch", "material": "Polished Marble Composite", "finish": "Dual Tone Gloss", "base_price": 34000, "price_delta": 0, "sku": "SRA-BD-13-15", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Kailash Shiv Parvati Ganesha Sanatan Family Statue",
        "slug": "kailash-shiv-parvati-ganesha-sanatan-family-statue",
        "deity": "Shiv Parivar",
        "deity_form": "Bhagwan Shiva, Mata Parvati, and Bal Ganesha on Kailash",
        "material": "White Marble Resin Composite",
        "material_purity": "Fine Marble Resin with Hand-Painted Details",
        "base_price": 68000,
        "original_price": 75000,
        "discount_badge": "Divine Family Blessing",
        "sku": "SRA-SP-14",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Grand Shiv Parivar murti with Mahadev, Parvati Ji, Bal Ganesha, Nandi, Trishul, and Ganga stream.",
        "long_description": "Brings family harmony, peace, strength, and complete spiritual auspiciousness to the household.",
        "certificate_number": "SRA-CERT-2026-SP14",
        "is_featured_masterpiece": True,
        "featured_order": 8,
        "specifications": {"Weight": "19.5 kg", "Finish": "Hand-Painted White Marble & Gold", "Craftsmanship Time": "32 Days"},
        "seva_guidelines": {"Abhishekam": "Rinse gently with Gangajal.", "Placement": "Primary home temple altar"},
        "images": [{"url": "/static/idols/kailash-shiv-parvati-ganesha.png", "alt": "Kailash Shiv Parvati Ganesha Sanatan Family Statue", "is_primary": True}],
        "tags": ["Shiv Parivar", "Shiva", "Parvati", "Ganesha", "Kailash"],
        "variants": [{"size": "18-inch", "material": "White Marble Resin", "finish": "Hand-Painted", "base_price": 68000, "price_delta": 0, "sku": "SRA-SP-14-18", "stock": {"JPR": 2, "KSH": 2}}],
    },
    {
        "name": "Neel Varna Bal Gopal Gold Matki Idol",
        "slug": "neel-varna-bal-gopal-gold-matki-idol",
        "deity": "Bal Krishna",
        "deity_form": "Shyam Varna Bal Krishna with Gold Foil Matki",
        "material": "Vibrant Blue Marble Resin",
        "material_purity": "Poly-Resin Matrix with 24K Gold Foil Garments",
        "base_price": 26000,
        "original_price": 30000,
        "discount_badge": "Shyam Varna Special",
        "sku": "SRA-BG-15",
        "atelier": "Jaipur Atelier",
        "short_description": "Vibrant ocean-blue Bal Gopal adorned with golden dhoti eating butter from a golden matki.",
        "long_description": "Captures the enchanting celestial color of Shyam Sundar Bal Gopal.",
        "certificate_number": "SRA-CERT-2026-BG15",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "7.5 kg", "Finish": "Vibrant Blue & Gold Foil", "Craftsmanship Time": "14 Days"},
        "seva_guidelines": {"Abhishekam": "Clean with damp microfiber cloth.", "Placement": "Puja mandir"},
        "images": [{"url": "/static/idols/neel-varna-bal-gopal-gold-matki.png", "alt": "Neel Varna Bal Gopal Gold Matki Idol", "is_primary": True}],
        "tags": ["Bal Gopal", "Shyam Varna", "Makhan Chor", "Gold Foil"],
        "variants": [{"size": "11-inch", "material": "Blue Marble Resin", "finish": "Gold Foil", "base_price": 26000, "price_delta": 0, "sku": "SRA-BG-15-11", "stock": {"JPR": 5, "KSH": 3}}],
    },
    {
        "name": "Shri Khatu Shyam Ji Sheesh Avatar Idol",
        "slug": "shri-khatu-shyam-ji-sheesh-avatar-idol",
        "deity": "Khatu Shyam Ji",
        "deity_form": "Sacred Sheesh Form of Barbarika",
        "material": "Pure White Marble",
        "material_purity": "Grade-A White Marble with Hand-Carved Garlands",
        "base_price": 48000,
        "original_price": 54000,
        "discount_badge": "Haare Ka Sahara",
        "sku": "SRA-KS-16",
        "atelier": "Jaipur Atelier",
        "short_description": "Holy Sheesh avatar of Shri Khatu Shyam Ji with gold mukut and triple white rose garlands.",
        "long_description": "Base carved with sacred gold inscription 'श्री श्याम देवाय नम:'. Known as Haare Ka Sahara.",
        "certificate_number": "SRA-CERT-2026-KS16",
        "is_featured_masterpiece": True,
        "featured_order": 9,
        "specifications": {"Weight": "13.2 kg", "Finish": "White Marble & Gold Mukut", "Craftsmanship Time": "22 Days"},
        "seva_guidelines": {"Abhishekam": "Offer fresh rose flowers and water cleaning.", "Placement": "Primary home temple"},
        "images": [{"url": "/static/idols/khatu-shyam-ji-sheesh-avatar.png", "alt": "Shri Khatu Shyam Ji Sheesh Avatar Idol", "is_primary": True}],
        "tags": ["Khatu Shyam Ji", "Sheesh Avatar", "White Marble", "Khatu Naresh"],
        "variants": [{"size": "15-inch", "material": "Pure White Marble", "finish": "Gold Inscribed Base", "base_price": 48000, "price_delta": 0, "sku": "SRA-KS-16-15", "stock": {"JPR": 4, "KSH": 4}}],
    },
    {
        "name": "Golden Brass-Finish Meditating Dhyana Buddha Statue",
        "slug": "golden-brass-finish-meditating-dhyana-buddha-statue",
        "deity": "Gautam Buddha",
        "deity_form": "Dhyana Buddha on Intricate Lotus Base",
        "material": "Metallic Resin Composite",
        "material_purity": "Bronze-Pigmented Resin Matrix",
        "base_price": 31000,
        "original_price": 35000,
        "discount_badge": "Antique Metallic",
        "sku": "SRA-BD-17",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Deeply meditative Buddha statue with lustrous antique gold-brass metallic finish.",
        "long_description": "Features an ornate multi-layered lotus throne pedestal giving an authentic antique bronze appearance.",
        "certificate_number": "SRA-CERT-2026-BD17",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "9.5 kg", "Finish": "Antique Brass Metallic", "Craftsmanship Time": "16 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with dry microfiber cloth.", "Placement": "Study or mediation table"},
        "images": [{"url": "/static/idols/golden-brass-dhyana-buddha.png", "alt": "Golden Brass-Finish Meditating Dhyana Buddha Statue", "is_primary": True}],
        "tags": ["Buddha", "Golden Brass", "Dhyana", "Lotus Base"],
        "variants": [{"size": "14-inch", "material": "Metallic Resin", "finish": "Antique Brass", "base_price": 31000, "price_delta": 0, "sku": "SRA-BD-17-14", "stock": {"JPR": 3, "KSH": 3}}],
    },
    {
        "name": "Kadamba Vriksha Radha Krishna Prem Leela Statue",
        "slug": "kadamba-vriksha-radha-krishna-prem-leela-statue",
        "deity": "Radha Krishna",
        "deity_form": "Radha Krishna under Sacred Kadamba Tree",
        "material": "White Marble Resin Composite",
        "material_purity": "Resin Composite with Hand-Carved Tree Bark Texture",
        "base_price": 54000,
        "original_price": 60000,
        "discount_badge": "Prem Leela",
        "sku": "SRA-RK-18",
        "atelier": "Jaipur Atelier",
        "short_description": "Krishna sitting under Kadamba tree playing flute while Radha sits gazing affectionately.",
        "long_description": "Artfully sculpted with textured dark wooden bark and warm yellow earth base.",
        "certificate_number": "SRA-CERT-2026-RK18",
        "is_featured_masterpiece": True,
        "featured_order": 10,
        "specifications": {"Weight": "16.0 kg", "Finish": "White Marble & Textured Wood", "Craftsmanship Time": "26 Days"},
        "seva_guidelines": {"Abhishekam": "Clean softly with cotton pad.", "Placement": "Living room temple"},
        "images": [{"url": "/static/idols/kadamba-vriksha-radha-krishna.png", "alt": "Kadamba Vriksha Radha Krishna Prem Leela Statue", "is_primary": True}],
        "tags": ["Radha Krishna", "Kadamba Tree", "Prem Leela", "Marble Resin"],
        "variants": [{"size": "16-inch", "material": "White Marble Resin", "finish": "Textured Wood Base", "base_price": 54000, "price_delta": 0, "sku": "SRA-RK-18-16", "stock": {"JPR": 2, "KSH": 2}}],
    },
    {
        "name": "Pink & Gold Muralidhar Krishna with Swan Statue",
        "slug": "pink-and-gold-muralidhar-krishna-with-swan-statue",
        "deity": "Shri Krishna",
        "deity_form": "Tribhanga Krishna with Flying Pink Dupatta & Golden Swan",
        "material": "White Marble Composite",
        "material_purity": "High-Density Marble Resin with Hand-Painted Dupatta",
        "base_price": 39000,
        "original_price": 44000,
        "discount_badge": "Swan Grace",
        "sku": "SRA-KR-19",
        "atelier": "Jaipur Atelier",
        "short_description": "Dynamic white marble Krishna playing flute with flowing pink dupatta and golden swan.",
        "long_description": "Stands gracefully upon a colorful lotus mound with a golden swan at his lotus feet.",
        "certificate_number": "SRA-CERT-2026-KR19",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "10.5 kg", "Finish": "Pink & Gold Hand-Painted", "Craftsmanship Time": "20 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe gently with damp cloth.", "Placement": "Home mandir"},
        "images": [{"url": "/static/idols/pink-gold-muralidhar-krishna-swan.png", "alt": "Pink & Gold Muralidhar Krishna with Swan Statue", "is_primary": True}],
        "tags": ["Krishna", "Muralidhar", "Swan", "Pink Dupatta"],
        "variants": [{"size": "15-inch", "material": "White Marble Composite", "finish": "Pink & Gold", "base_price": 39000, "price_delta": 0, "sku": "SRA-KR-19-15", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "White Shvetambara Radha Krishna with Gau Mata Statue",
        "slug": "white-shvetambara-radha-krishna-with-gau-mata-statue",
        "deity": "Radha Krishna",
        "deity_form": "Shvetambara Radha Krishna with Sacred Cow",
        "material": "Pure White Marble",
        "material_purity": "Pure White Marble with Emerald Green & Gold Trim",
        "base_price": 49000,
        "original_price": 55000,
        "discount_badge": "Sacred Gau Seva",
        "sku": "SRA-RK-20",
        "atelier": "Jaipur Atelier",
        "short_description": "Crisp white marble Radha Krishna pair with green-gold borders and sacred white cow.",
        "long_description": "Features dark rock pedestal base, pink bansuri tassels, and serene facial carving.",
        "certificate_number": "SRA-CERT-2026-RK20",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "13.8 kg", "Finish": "Green-Gold Trim on White Marble", "Craftsmanship Time": "24 Days"},
        "seva_guidelines": {"Abhishekam": "Suitable for regular snana with pure water.", "Placement": "Main prayer room"},
        "images": [{"url": "/static/idols/shvetambara-radha-krishna-gau-mata.png", "alt": "White Shvetambara Radha Krishna with Gau Mata Statue", "is_primary": True}],
        "tags": ["Radha Krishna", "Shvetambara", "Gau Mata", "White Marble"],
        "variants": [{"size": "16-inch", "material": "Pure White Marble", "finish": "Green-Gold Border", "base_price": 49000, "price_delta": 0, "sku": "SRA-RK-20-16", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Pink Lotus Shvetambara Radha Krishna Pair",
        "slug": "pink-lotus-shvetambara-radha-krishna-pair",
        "deity": "Radha Krishna",
        "deity_form": "Radha Krishna on Large Blooming Pink Lotus",
        "material": "White Marble Composite",
        "material_purity": "Resin Composite with Gold Brocade Trimming",
        "base_price": 46000,
        "original_price": 52000,
        "discount_badge": "Lotus Throne",
        "sku": "SRA-RK-21",
        "atelier": "Jaipur Atelier",
        "short_description": "White and gold clad Radha Krishna pair standing inside a large pink lotus flower base.",
        "long_description": "Radha leans lovingly against Krishna's shoulder as he plays the bansuri.",
        "certificate_number": "SRA-CERT-2026-RK21",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "12.4 kg", "Finish": "Gold Brocade & Pink Lotus Base", "Craftsmanship Time": "22 Days"},
        "seva_guidelines": {"Abhishekam": "Clean with damp cloth.", "Placement": "Temple sanctuary"},
        "images": [{"url": "/static/idols/pink-lotus-radha-krishna-pair.png", "alt": "Pink Lotus Shvetambara Radha Krishna Pair", "is_primary": True}],
        "tags": ["Radha Krishna", "Pink Lotus", "Shvetambara", "Gold Brocade"],
        "variants": [{"size": "15-inch", "material": "White Marble Composite", "finish": "Pink Lotus Base", "base_price": 46000, "price_delta": 0, "sku": "SRA-RK-21-15", "stock": {"JPR": 4, "KSH": 2}}],
    },
    {
        "name": "Paan Patta Green Leaf Ganesha Idol",
        "slug": "paan-patta-green-leaf-ganesha-idol",
        "deity": "Lord Ganesha",
        "deity_form": "Ganesha Seated on Emerald Green Sacred Leaf",
        "material": "High-Gloss Marble Resin",
        "material_purity": "Resin Composite with Emerald Lacquer Finish",
        "base_price": 22000,
        "original_price": 26000,
        "discount_badge": "Auspicious Entrance",
        "sku": "SRA-GN-22",
        "atelier": "Jaipur Atelier",
        "short_description": "Auspicious white Ganesha seated inside a high-gloss emerald green Paan leaf backrest.",
        "long_description": "Adorned with golden crown and trunk ornaments. Ideal for home entrances and car dashboards/desks.",
        "certificate_number": "SRA-CERT-2026-GN22",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "5.5 kg", "Finish": "Glossy Emerald Green Leaf & White Ganesha", "Craftsmanship Time": "12 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe clean with cloth.", "Placement": "Foyer, entrance, or desk"},
        "images": [{"url": "/static/idols/paan-patta-green-leaf-ganesha.png", "alt": "Paan Patta Green Leaf Ganesha Idol", "is_primary": True}],
        "tags": ["Ganesha", "Paan Leaf", "Auspicious", "Green Leaf"],
        "variants": [{"size": "9-inch", "material": "Marble Resin", "finish": "Emerald Gloss", "base_price": 22000, "price_delta": 0, "sku": "SRA-GN-22-09", "stock": {"JPR": 6, "KSH": 5}}],
    },
    {
        "name": "Swarna Vastra Kamadhenu Krishna Masterpiece",
        "slug": "swarna-vastra-kamadhenu-krishna-masterpiece",
        "deity": "Shri Krishna",
        "deity_form": "24K Gold Leaf Draped Krishna with Kamadhenu Cow",
        "material": "Pure Marble Composite & 24K Gold Leaf",
        "material_purity": "24K Genuine Gold Foil Layering on White Marble Base",
        "base_price": 75000,
        "original_price": 85000,
        "discount_badge": "Masterpiece Gold",
        "sku": "SRA-KR-23",
        "atelier": "Jaipur Atelier",
        "short_description": "Royal flagship edition of Krishna draped in 24K gold foil vastra with Kamadhenu cow.",
        "long_description": "Masterpiece crafted by Jaipur senior sculptors featuring cloud base and gold-filigree rim pedestal.",
        "certificate_number": "SRA-CERT-2026-KR23",
        "is_featured_masterpiece": True,
        "featured_order": 1,
        "specifications": {"Weight": "17.5 kg", "Finish": "24K Gold Leaf & Polished Marble", "Craftsmanship Time": "35 Days"},
        "seva_guidelines": {"Abhishekam": "Gentle Gangajal wipe; protect gold foil coating.", "Placement": "Central temple sanctum"},
        "images": [{"url": "/static/idols/swarna-vastra-kamadhenu-krishna.png", "alt": "Swarna Vastra Kamadhenu Krishna Masterpiece", "is_primary": True}],
        "tags": ["Krishna", "24K Gold Leaf", "Masterpiece", "Kamadhenu"],
        "variants": [{"size": "18-inch", "material": "24K Gold Foil Marble", "finish": "Gold Leaf", "base_price": 75000, "price_delta": 0, "sku": "SRA-KR-23-18", "stock": {"JPR": 2, "KSH": 1}}],
    },
    {
        "name": "Pure White Marble Radha Krishna Under Tree Sculpture",
        "slug": "pure-white-marble-radha-krishna-under-tree-sculpture",
        "deity": "Radha Krishna",
        "deity_form": "Monochromatic White Marble Tree Scene",
        "material": "Pure Makrana White Marble",
        "material_purity": "Single Block Pure White Marble",
        "base_price": 56000,
        "original_price": 62000,
        "discount_badge": "Monochrome Perfection",
        "sku": "SRA-RK-24",
        "atelier": "Jaipur Atelier",
        "short_description": "Pure white marble sculpture of Radha Krishna under tree with subtle gold accents.",
        "long_description": "Monochromatic masterwork capturing Krishna seated on a tree branch playing flute for Radha.",
        "certificate_number": "SRA-CERT-2026-RK24",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "16.2 kg", "Finish": "Pure White Polished Marble", "Craftsmanship Time": "28 Days"},
        "seva_guidelines": {"Abhishekam": "Suitable for regular holy snana.", "Placement": "Home mandir"},
        "images": [{"url": "/static/idols/pure-white-radha-krishna-tree.png", "alt": "Pure White Marble Radha Krishna Under Tree Sculpture", "is_primary": True}],
        "tags": ["Radha Krishna", "Pure White Marble", "Monochrome", "Makrana"],
        "variants": [{"size": "16-inch", "material": "Pure White Marble", "finish": "Polished White", "base_price": 56000, "price_delta": 0, "sku": "SRA-RK-24-16", "stock": {"JPR": 2, "KSH": 2}}],
    },
    {
        "name": "Sherawali Durga Maa Tiger Swar Murti",
        "slug": "sherawali-durga-maa-tiger-swar-murti",
        "deity": "Goddess Durga",
        "deity_form": "Ashtabhuja Durga Riding Golden Tiger",
        "material": "White Marble Resin Composite",
        "material_purity": "Resin Composite with Gold Foil Corona",
        "base_price": 62000,
        "original_price": 70000,
        "discount_badge": "Navratri Edition",
        "sku": "SRA-DG-25",
        "atelier": "Kashi Sanctum Studio",
        "short_description": "Ashtabhuja Durga Maa riding a golden tiger with 8 sacred weapons and golden sun halo.",
        "long_description": "Radiates power, divine strength, protection, and victory over evil.",
        "certificate_number": "SRA-CERT-2026-DG25",
        "is_featured_masterpiece": True,
        "featured_order": 11,
        "specifications": {"Weight": "18.0 kg", "Finish": "Golden Tiger & Sun Halo", "Craftsmanship Time": "30 Days"},
        "seva_guidelines": {"Abhishekam": "Clean softly with cotton cloth.", "Placement": "East sanctum wall"},
        "images": [{"url": "/static/idols/sherawali-durga-maa-tiger.png", "alt": "Sherawali Durga Maa Tiger Swar Murti", "is_primary": True}],
        "tags": ["Durga Maa", "Sherawali", "Tiger", "Ashtabhuja"],
        "variants": [{"size": "18-inch", "material": "White Marble Resin", "finish": "Golden Tiger", "base_price": 62000, "price_delta": 0, "sku": "SRA-DG-25-18", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Vrindavan Kunj Radha Krishna Color Statue",
        "slug": "vrindavan-kunj-radha-krishna-color-statue",
        "deity": "Radha Krishna",
        "deity_form": "Colorful Radha Krishna under Tree in Magenta & Lime Green",
        "material": "Hand-Painted Resin Composite",
        "material_purity": "High-Strength Polymer Matrix",
        "base_price": 47000,
        "original_price": 53000,
        "discount_badge": "Vrindavan Kunj",
        "sku": "SRA-RK-26",
        "atelier": "Jaipur Atelier",
        "short_description": "Colorful sculpture of Krishna in lime green dhoti and saffron shawl with Radha in magenta pink saree.",
        "long_description": "Brings the lively colors of Vrindavan kunja into your home altar.",
        "certificate_number": "SRA-CERT-2026-RK26",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "13.0 kg", "Finish": "Vibrant Hand-Painted Resin", "Craftsmanship Time": "22 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with damp cloth.", "Placement": "Living room temple"},
        "images": [{"url": "/static/idols/vrindavan-kunj-radha-krishna.png", "alt": "Vrindavan Kunj Radha Krishna Color Statue", "is_primary": True}],
        "tags": ["Radha Krishna", "Vrindavan", "Magenta", "Hand-Painted"],
        "variants": [{"size": "15-inch", "material": "Hand-Painted Resin", "finish": "Vibrant Colors", "base_price": 47000, "price_delta": 0, "sku": "SRA-RK-26-15", "stock": {"JPR": 3, "KSH": 3}}],
    },
    {
        "name": "White Shvetambara Krishna Kamadhenu Pink Lotus Idol",
        "slug": "white-shvetambara-krishna-kamadhenu-pink-lotus-idol",
        "deity": "Shri Krishna",
        "deity_form": "Krishna with Cow on Blooming Pink Lotus Base",
        "material": "White Marble Composite",
        "material_purity": "White Marble Resin with Pink Lotus Pedestal",
        "base_price": 37500,
        "original_price": 42000,
        "discount_badge": "Lotus Blessing",
        "sku": "SRA-KR-27",
        "atelier": "Jaipur Atelier",
        "short_description": "White marble Krishna playing flute beside Kamadhenu cow standing on a pink lotus base.",
        "long_description": "Finished with gold brocade trimming and serene facial carving.",
        "certificate_number": "SRA-CERT-2026-KR27",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "10.0 kg", "Finish": "White Marble & Pink Lotus Base", "Craftsmanship Time": "18 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe gently with damp cloth.", "Placement": "Home prayer area"},
        "images": [{"url": "/static/idols/shvetambara-krishna-lotus-cow.png", "alt": "White Shvetambara Krishna Kamadhenu Pink Lotus Idol", "is_primary": True}],
        "tags": ["Krishna", "Kamadhenu", "Pink Lotus", "Shvetambara"],
        "variants": [{"size": "14-inch", "material": "White Marble Composite", "finish": "Pink Lotus Base", "base_price": 37500, "price_delta": 0, "sku": "SRA-KR-27-14", "stock": {"JPR": 4, "KSH": 2}}],
    },
    {
        "name": "Sky Blue Neel Kanth Muralidhar Krishna Murti",
        "slug": "sky-blue-neel-kanth-muralidhar-krishna-murti",
        "deity": "Shri Krishna",
        "deity_form": "Sky Blue Krishna in Magenta & Lime Green Vastra",
        "material": "Polymer Marble Matrix",
        "material_purity": "Pigmented Resin Matrix with Gold Trimming",
        "base_price": 33000,
        "original_price": 37000,
        "discount_badge": "Neel Kanth",
        "sku": "SRA-KR-28",
        "atelier": "Jaipur Atelier",
        "short_description": "Radiant sky blue skin tone Krishna standing in Tribhanga pose with golden flute.",
        "long_description": "Draped in magenta waistcloth and lime green dupatta on a pink lotus base.",
        "certificate_number": "SRA-CERT-2026-KR28",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "9.2 kg", "Finish": "Sky Blue & Gold Finish", "Craftsmanship Time": "16 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe dry after cleaning.", "Placement": "Home altar"},
        "images": [{"url": "/static/idols/sky-blue-muralidhar-krishna.png", "alt": "Sky Blue Neel Kanth Muralidhar Krishna Murti", "is_primary": True}],
        "tags": ["Krishna", "Sky Blue", "Neel Kanth", "Muralidhar"],
        "variants": [{"size": "13-inch", "material": "Polymer Marble Matrix", "finish": "Sky Blue", "base_price": 33000, "price_delta": 0, "sku": "SRA-KR-28-13", "stock": {"JPR": 4, "KSH": 3}}],
    },
    {
        "name": "Azure Blue Pitambari Krishna Bansuri Idol",
        "slug": "azure-blue-pitambari-krishna-bansuri-idol",
        "deity": "Shri Krishna",
        "deity_form": "Azure Blue Krishna in Bright Yellow Pitambari",
        "material": "Polymer Marble Composite",
        "material_purity": "Azure Pigmented Resin with Yellow Lacquer",
        "base_price": 35000,
        "original_price": 39000,
        "discount_badge": "Pitambari Special",
        "sku": "SRA-KR-29",
        "atelier": "Jaipur Atelier",
        "short_description": "Deep azure blue Krishna with bright yellow pitambari shawl playing gold bansuri.",
        "long_description": "Classic iconography of Shyam Sundar Pitambari Dhari.",
        "certificate_number": "SRA-CERT-2026-KR29",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "9.6 kg", "Finish": "Azure Blue & Yellow Pitambari", "Craftsmanship Time": "17 Days"},
        "seva_guidelines": {"Abhishekam": "Clean gently with soft cloth.", "Placement": "Prayer altar"},
        "images": [{"url": "/static/idols/azure-blue-pitambari-krishna.png", "alt": "Azure Blue Pitambari Krishna Bansuri Idol", "is_primary": True}],
        "tags": ["Krishna", "Azure Blue", "Pitambari", "Bansuri"],
        "variants": [{"size": "14-inch", "material": "Polymer Marble Composite", "finish": "Azure & Yellow", "base_price": 35000, "price_delta": 0, "sku": "SRA-KR-29-14", "stock": {"JPR": 3, "KSH": 3}}],
    },
    {
        "name": "Divya Prabhawali White Marble Krishna Murti",
        "slug": "divya-prabhawali-white-marble-krishna-murti",
        "deity": "Shri Krishna",
        "deity_form": "White Marble Krishna with Gold Halo Backdrop",
        "material": "Pure White Marble",
        "material_purity": "Grade-A Makrana Marble with Sun Aura Backdrop",
        "base_price": 41000,
        "original_price": 46000,
        "discount_badge": "Divya Prabha",
        "sku": "SRA-KR-30",
        "atelier": "Jaipur Atelier",
        "short_description": "Pure white marble Krishna featuring a radiant gold halo aura behind his head.",
        "long_description": "Draped in white dhoti with green edge and golden ornaments.",
        "certificate_number": "SRA-CERT-2026-KR30",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "11.8 kg", "Finish": "Polished White & Gold Halo", "Craftsmanship Time": "20 Days"},
        "seva_guidelines": {"Abhishekam": "Suitable for regular holy snana.", "Placement": "Home mandir"},
        "images": [{"url": "/static/idols/divya-prabhawali-krishna.png", "alt": "Divya Prabhawali White Marble Krishna Murti", "is_primary": True}],
        "tags": ["Krishna", "White Marble", "Gold Halo", "Prabhawali"],
        "variants": [{"size": "15-inch", "material": "Pure White Marble", "finish": "Gold Halo", "base_price": 41000, "price_delta": 0, "sku": "SRA-KR-30-15", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Seated Krishna with Calf Marble Sculpture",
        "slug": "seated-krishna-with-calf-marble-sculpture",
        "deity": "Shri Krishna",
        "deity_form": "Seated Krishna Playing Bansuri with Loving Calf",
        "material": "White Marble Composite",
        "material_purity": "White Marble Resin with Gold Threadwork",
        "base_price": 36500,
        "original_price": 41000,
        "discount_badge": "Gau Vatsa Love",
        "sku": "SRA-KR-31",
        "atelier": "Jaipur Atelier",
        "short_description": "Seated white marble Krishna playing bansuri while a calf looks up reverently.",
        "long_description": "Features ornate gold threadwork dhoti and pink floral garlands on white lotus.",
        "certificate_number": "SRA-CERT-2026-KR31",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "10.2 kg", "Finish": "White Marble & Gold Threadwork", "Craftsmanship Time": "18 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with soft cloth.", "Placement": "Sanctum table"},
        "images": [{"url": "/static/idols/seated-krishna-with-calf.png", "alt": "Seated Krishna with Calf Marble Sculpture", "is_primary": True}],
        "tags": ["Krishna", "Seated Krishna", "Calf", "Gold Threadwork"],
        "variants": [{"size": "13-inch", "material": "White Marble Composite", "finish": "Gold Threadwork", "base_price": 36500, "price_delta": 0, "sku": "SRA-KR-31-13", "stock": {"JPR": 4, "KSH": 2}}],
    },
    {
        "name": "Surya Prabha Mandala Krishna Murti",
        "slug": "surya-prabha-mandala-krishna-murti",
        "deity": "Shri Krishna",
        "deity_form": "Krishna with Pink-Yellow Surya Prabha Mandala",
        "material": "Hand-Painted Resin Composite",
        "material_purity": "Poly-Resin Matrix with Multi-Color Lacquer",
        "base_price": 43000,
        "original_price": 48000,
        "discount_badge": "Surya Mandala",
        "sku": "SRA-KR-32",
        "atelier": "Jaipur Atelier",
        "short_description": "Shri Krishna surrounded by a multi-color pink and yellow sun-halo (Surya Prabha Mandala).",
        "long_description": "Draped in lime green dupatta and pink-turquoise dhoti playing golden flute.",
        "certificate_number": "SRA-CERT-2026-KR32",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "11.5 kg", "Finish": "Multi-Color Sun Halo", "Craftsmanship Time": "21 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with damp cloth.", "Placement": "Main prayer room"},
        "images": [{"url": "/static/idols/surya-prabha-mandala-krishna.png", "alt": "Surya Prabha Mandala Krishna Murti", "is_primary": True}],
        "tags": ["Krishna", "Surya Mandala", "Sun Halo", "Multi-Color"],
        "variants": [{"size": "15-inch", "material": "Resin Composite", "finish": "Sun Halo Finish", "base_price": 43000, "price_delta": 0, "sku": "SRA-KR-32-15", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Yashoda Damodara Bandhan Leela Statue",
        "slug": "yashoda-damodara-bandhan-leela-statue",
        "deity": "Yashoda & Bal Krishna",
        "deity_form": "Yashoda Tying Bal Krishna to Ukhal (Damodara Leela)",
        "material": "Hand-Painted Marble Composite",
        "material_purity": "Resin Composite with Gold Rope Detailing",
        "base_price": 34000,
        "original_price": 38000,
        "discount_badge": "Damodara Leela",
        "sku": "SRA-YK-33",
        "atelier": "Jaipur Atelier",
        "short_description": "Mata Yashoda tying young Bal Krishna to wooden mortar (Ukhal) with golden rope.",
        "long_description": "Celebrates the sacred Damodara Leela — bound only by boundless love and devotion.",
        "certificate_number": "SRA-CERT-2026-YK33",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "9.0 kg", "Finish": "Yellow & Pink Hand-Painted", "Craftsmanship Time": "17 Days"},
        "seva_guidelines": {"Abhishekam": "Wipe with microfiber cloth.", "Placement": "Home prayer area"},
        "images": [{"url": "/static/idols/yashoda-damodara-bandhan-leela.png", "alt": "Yashoda Damodara Bandhan Leela Statue", "is_primary": True}],
        "tags": ["Yashoda", "Bal Krishna", "Damodara Leela", "Ukhal"],
        "variants": [{"size": "12-inch", "material": "Marble Composite", "finish": "Gold Rope Accent", "base_price": 34000, "price_delta": 0, "sku": "SRA-YK-33-12", "stock": {"JPR": 3, "KSH": 2}}],
    },
    {
        "name": "Shvetambara Prabhawali Muralidhar Krishna Statue",
        "slug": "shvetambara-prabhawali-muralidhar-krishna-statue",
        "deity": "Shri Krishna",
        "deity_form": "White Marble Krishna with Gold Halo on Wooden Base",
        "material": "Pure White Makrana Marble",
        "material_purity": "Grade-A White Marble on Polished Wood Base",
        "base_price": 44000,
        "original_price": 50000,
        "discount_badge": "Sacred Glow",
        "sku": "SRA-KR-34",
        "atelier": "Jaipur Atelier",
        "short_description": "White marble standing Krishna with gold sun halo aura on a polished wood-look base.",
        "long_description": "Draped in gold-trimmed white vastra playing flute with serene radiance.",
        "certificate_number": "SRA-CERT-2026-KR34",
        "is_featured_masterpiece": False,
        "specifications": {"Weight": "12.0 kg", "Finish": "Pure White & Gold Halo on Wooden Base", "Craftsmanship Time": "22 Days"},
        "seva_guidelines": {"Abhishekam": "Clean softly with cotton cloth.", "Placement": "Home temple"},
        "images": [{"url": "/static/idols/shvetambara-prabhawali-muralidhar-krishna.png", "alt": "Shvetambara Prabhawali Muralidhar Krishna Statue", "is_primary": True}],
        "tags": ["Krishna", "White Marble", "Wood Base", "Gold Halo"],
        "variants": [{"size": "16-inch", "material": "Pure White Marble", "finish": "Gold Halo & Wood Base", "base_price": 44000, "price_delta": 0, "sku": "SRA-KR-34-16", "stock": {"JPR": 3, "KSH": 3}}],
    },
]


async def seed_database(force_reseed: bool = False):
    async with async_session_factory() as db:
        if not force_reseed:
            loc_res = await db.execute(select(Location))
            existing_loc = loc_res.scalars().first()
            prod_res = await db.execute(select(Product))
            existing_prods = prod_res.scalars().all()
            if existing_loc and len(existing_prods) >= 30:
                logger.info(f"Database already seeded with {len(existing_prods)} products.")
                return

        logger.info("Starting database seed with 34 handcrafted idols...")

        # 1. Locations
        loc_res = await db.execute(select(Location))
        locations = {loc.code: loc for loc in loc_res.scalars().all()}

        if "JPR" not in locations:
            jaipur = Location(
                id=str(uuid.uuid4()),
                code="JPR",
                name="Jaipur Artisan Atelier",
                address="Johari Bazaar, Pink City",
                city="Jaipur",
                state="Rajasthan",
                is_active=True,
            )
            db.add(jaipur)
            locations["JPR"] = jaipur

        if "KSH" not in locations:
            kashi = Location(
                id=str(uuid.uuid4()),
                code="KSH",
                name="Kashi Sanctum Studio",
                address="Assi Ghat Marg",
                city="Varanasi",
                state="Uttar Pradesh",
                is_active=True,
            )
            db.add(kashi)
            locations["KSH"] = kashi

        await db.flush()

        # 2. Staff and Admin Users
        user_res = await db.execute(select(User).where(User.email == "acharya@siyaramarts.com"))
        if not user_res.scalars().first():
            admin_user = User(
                id=str(uuid.uuid4()),
                clerk_user_id="user_admin_siyaram_01",
                email="acharya@siyaramarts.com",
                first_name="Acharya",
                last_name="Sharma",
                phone="+919829012345",
                role=UserRole.ADMIN,
            )
            staff_user = User(
                id=str(uuid.uuid4()),
                clerk_user_id="user_staff_siyaram_02",
                email="atelier.manager@siyaramarts.com",
                first_name="Radheshyam",
                last_name="Verma",
                phone="+919829054321",
                role=UserRole.STAFF,
            )
            db.add_all([admin_user, staff_user])
            await db.flush()

        # 3. Products
        loc_map = {"JPR": locations["JPR"].id, "KSH": locations["KSH"].id}

        for pdata in IDOL_PRODUCTS_DATA:
            existing_p = await db.execute(select(Product).where(Product.sku == pdata["sku"]))
            if existing_p.scalars().first():
                continue

            variants_list = pdata.pop("variants")
            prod = Product(id=str(uuid.uuid4()), **pdata)
            db.add(prod)
            await db.flush()

            for vdata in variants_list:
                stock_dict = vdata.pop("stock")
                variant = ProductVariant(
                    id=str(uuid.uuid4()),
                    product_id=prod.id,
                    **vdata,
                )
                db.add(variant)
                await db.flush()

                # Add inventory items for locations
                for loc_code, count in stock_dict.items():
                    loc_id = loc_map[loc_code]
                    inv_item = InventoryItem(
                        id=str(uuid.uuid4()),
                        variant_id=variant.id,
                        location_id=loc_id,
                        stock_count=count,
                        reserved_count=0,
                        low_stock_threshold=2,
                    )
                    db.add(inv_item)

                    ledger = StockLedgerEntry(
                        variant_id=variant.id,
                        location_id=loc_id,
                        delta=count,
                        reason=LedgerReason.RESTOCK,
                        actor="initial_seed",
                        reference_id=f"INIT-{variant.sku}",
                        note="Initial atelier stock onboarding",
                    )
                    db.add(ledger)

        await db.commit()
        logger.info("Successfully seeded database with all 34 handcrafted idols and initial stock!")


if __name__ == "__main__":
    asyncio.run(seed_database(force_reseed=True))
