"""add pdf_status to invoices

Revision ID: 78aaf951099c
Revises: 1d8967b426af
Create Date: 2026-09-07 00:10:40.195199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78aaf951099c'
down_revision: Union[str, Sequence[str], None] = '1d8967b426af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pdf_status', sa.Enum('PENDING', 'GENERATED', 'FAILED', name='pdf_status_enum', native_enum=False), nullable=False))
    op.create_index(op.f('ix_invoices_pdf_status'), 'invoices', ['pdf_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_pdf_status'), table_name='invoices')
    op.drop_column('invoices', 'pdf_status')
    # ### end Alembic commands ###
